### PR TITLE
Code cleanup, master merge and improved tests

### PR DESCRIPTION
**Pull request by drozdziak1**
This PR introduces everything from the title. Quick note on the tests: Babel seems to converge very fast on the routes that matter most (5s currently) but at the same time seems to barely care about the suboptimal ones and keeps routes which appear to contain cycles, therefore at the moment we only check the installed routes.

**If you're going to review this, please check if `test.sh` passes for you**

### CODE REVIEW

**Comment by drozdziak1** [comment]
This should go into `althea`, sorry!

**Comment by drozdziak1** [comment]
Okay, GitHub let me change the base.

**Comment by drozdziak1** [comment]
**Note:** my commits start at `6d21718d2e1750c355028f89304cda747f2c4ad7`

**Comment by jkilpatr** [comment]
looks ok to me, needs to be tested do not merge until it's very well tested. Since we build and ship master to real devices, we need to be very sure that interoperability etc happens.

**Pull request merged**
